port: 50051
postgres:
  schemaVersion: 1
  hostPort: 0.0.0.0:5432
  database: postgres
  user: postgres
  password: password
nats:
  hostPort: 0.0.0.0:4222
  embeddedNats: true
temporal:
  hostPort: 0.0.0.0:7233
  namespace: default
development:
  inMemory: false
  temporal: true
  logger: true
