// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: context.sql

package sqlc

import (
	"context"
)

const contextExists = `-- name: ContextExists :exec
SELECT id
FROM contexts
WHERE id = $1
`

func (q *Queries) ContextExists(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, contextExists, id)
	return err
}

const createContext = `-- name: CreateContext :exec
INSERT INTO contexts (id)
VALUES ($1)
`

func (q *Queries) CreateContext(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, createContext, id)
	return err
}
