// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package sqlc

import (
	"context"

	"github.com/annexsh/annex/test"
	"github.com/google/uuid"
)

type Querier interface {
	ContextExists(ctx context.Context, id string) error
	CreateCaseExecution(ctx context.Context, arg CreateCaseExecutionParams) (*CaseExecution, error)
	CreateContext(ctx context.Context, id string) error
	CreateGroup(ctx context.Context, arg CreateGroupParams) error
	CreateLog(ctx context.Context, arg CreateLogParams) error
	CreateTest(ctx context.Context, arg CreateTestParams) (*Test, error)
	CreateTestDefaultInput(ctx context.Context, arg CreateTestDefaultInputParams) error
	CreateTestExecution(ctx context.Context, arg CreateTestExecutionParams) (*TestExecution, error)
	CreateTestExecutionInput(ctx context.Context, arg CreateTestExecutionInputParams) error
	DeleteCaseExecution(ctx context.Context, arg DeleteCaseExecutionParams) error
	DeleteLog(ctx context.Context, id uuid.UUID) error
	GetCaseExecution(ctx context.Context, arg GetCaseExecutionParams) (*CaseExecution, error)
	GetLog(ctx context.Context, id uuid.UUID) (*Log, error)
	GetTest(ctx context.Context, id uuid.UUID) (*Test, error)
	GetTestByName(ctx context.Context, arg GetTestByNameParams) (*Test, error)
	GetTestDefaultInput(ctx context.Context, testID uuid.UUID) (*TestDefaultInput, error)
	GetTestExecution(ctx context.Context, id test.TestExecutionID) (*TestExecution, error)
	GetTestExecutionInput(ctx context.Context, testExecutionID test.TestExecutionID) (*TestExecutionInput, error)
	GroupExists(ctx context.Context, arg GroupExistsParams) error
	ListCaseExecutions(ctx context.Context, testExecutionID test.TestExecutionID) ([]*CaseExecution, error)
	ListLogs(ctx context.Context, testExecutionID test.TestExecutionID) ([]*Log, error)
	ListTestExecutions(ctx context.Context, arg ListTestExecutionsParams) ([]*TestExecution, error)
	ListTests(ctx context.Context) ([]*Test, error)
	ResetCaseExecution(ctx context.Context, arg ResetCaseExecutionParams) (*CaseExecution, error)
	UpdateCaseExecutionFinished(ctx context.Context, arg UpdateCaseExecutionFinishedParams) (*CaseExecution, error)
	UpdateCaseExecutionStarted(ctx context.Context, arg UpdateCaseExecutionStartedParams) (*CaseExecution, error)
	UpdateTestExecutionFinished(ctx context.Context, arg UpdateTestExecutionFinishedParams) (*TestExecution, error)
	UpdateTestExecutionStarted(ctx context.Context, arg UpdateTestExecutionStartedParams) (*TestExecution, error)
}

var _ Querier = (*Queries)(nil)
