// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: test.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createTest = `-- name: CreateTest :one
INSERT INTO tests (context, "group", id, name, has_input)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (context, "group", name) DO UPDATE
    SET has_input   = excluded.has_input,
        create_time = now()
RETURNING context, "group", id, name, has_input, create_time
`

type CreateTestParams struct {
	Context  string    `json:"context"`
	Group    string    `json:"group"`
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	HasInput bool      `json:"has_input"`
}

func (q *Queries) CreateTest(ctx context.Context, arg CreateTestParams) (*Test, error) {
	row := q.db.QueryRow(ctx, createTest,
		arg.Context,
		arg.Group,
		arg.ID,
		arg.Name,
		arg.HasInput,
	)
	var i Test
	err := row.Scan(
		&i.Context,
		&i.Group,
		&i.ID,
		&i.Name,
		&i.HasInput,
		&i.CreateTime,
	)
	return &i, err
}

const createTestDefaultInput = `-- name: CreateTestDefaultInput :exec
INSERT INTO test_default_inputs (test_id, data)
VALUES ($1, $2)
ON CONFLICT (test_id) DO UPDATE
    SET data = excluded.data
`

type CreateTestDefaultInputParams struct {
	TestID uuid.UUID `json:"test_id"`
	Data   []byte    `json:"data"`
}

func (q *Queries) CreateTestDefaultInput(ctx context.Context, arg CreateTestDefaultInputParams) error {
	_, err := q.db.Exec(ctx, createTestDefaultInput, arg.TestID, arg.Data)
	return err
}

const getTest = `-- name: GetTest :one
SELECT context, "group", id, name, has_input, create_time
FROM tests
WHERE id = $1
`

func (q *Queries) GetTest(ctx context.Context, id uuid.UUID) (*Test, error) {
	row := q.db.QueryRow(ctx, getTest, id)
	var i Test
	err := row.Scan(
		&i.Context,
		&i.Group,
		&i.ID,
		&i.Name,
		&i.HasInput,
		&i.CreateTime,
	)
	return &i, err
}

const getTestByName = `-- name: GetTestByName :one
SELECT context, "group", id, name, has_input, create_time
FROM tests
WHERE name = $1
  AND "group" = $2
`

type GetTestByNameParams struct {
	Name  string `json:"name"`
	Group string `json:"group"`
}

func (q *Queries) GetTestByName(ctx context.Context, arg GetTestByNameParams) (*Test, error) {
	row := q.db.QueryRow(ctx, getTestByName, arg.Name, arg.Group)
	var i Test
	err := row.Scan(
		&i.Context,
		&i.Group,
		&i.ID,
		&i.Name,
		&i.HasInput,
		&i.CreateTime,
	)
	return &i, err
}

const getTestDefaultInput = `-- name: GetTestDefaultInput :one
SELECT test_id, data
FROM test_default_inputs
WHERE test_id = $1
`

func (q *Queries) GetTestDefaultInput(ctx context.Context, testID uuid.UUID) (*TestDefaultInput, error) {
	row := q.db.QueryRow(ctx, getTestDefaultInput, testID)
	var i TestDefaultInput
	err := row.Scan(&i.TestID, &i.Data)
	return &i, err
}

const listTests = `-- name: ListTests :many
SELECT context, "group", id, name, has_input, create_time
FROM tests
`

func (q *Queries) ListTests(ctx context.Context) ([]*Test, error) {
	rows, err := q.db.Query(ctx, listTests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Test
	for rows.Next() {
		var i Test
		if err := rows.Scan(
			&i.Context,
			&i.Group,
			&i.ID,
			&i.Name,
			&i.HasInput,
			&i.CreateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
