DROP TABLE IF EXISTS tests CASCADE;
DROP TABLE IF EXISTS test_default_inputs CASCADE;
DROP TABLE IF EXISTS runners CASCADE;
DROP TABLE IF EXISTS test_executions CASCADE;
DROP TABLE IF EXISTS test_execution_inputs CASCADE;
DROP TABLE IF EXISTS case_executions CASCADE;
DROP TABLE IF EXISTS logs CASCADE;
