// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: test.sql

package sqlc

import (
	"context"
	"time"

	"github.com/annexsh/annex/uuid"
)

const createTest = `-- name: CreateTest :one
INSERT INTO tests (context_id, test_suite_id, id, name, has_input, create_time)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(context_id, test_suite_id, name) DO UPDATE
    SET has_input   = excluded.has_input
RETURNING id, context_id, test_suite_id, name, has_input, create_time
`

type CreateTestParams struct {
	ContextID   string    `json:"context_id"`
	TestSuiteID uuid.V7   `json:"test_suite_id"`
	ID          uuid.V7   `json:"id"`
	Name        string    `json:"name"`
	HasInput    bool      `json:"has_input"`
	CreateTime  time.Time `json:"create_time"`
}

func (q *Queries) CreateTest(ctx context.Context, arg CreateTestParams) (*Test, error) {
	row := q.db.QueryRowContext(ctx, createTest,
		arg.ContextID,
		arg.TestSuiteID,
		arg.ID,
		arg.Name,
		arg.HasInput,
		arg.CreateTime,
	)
	var i Test
	err := row.Scan(
		&i.ID,
		&i.ContextID,
		&i.TestSuiteID,
		&i.Name,
		&i.HasInput,
		&i.CreateTime,
	)
	return &i, err
}

const createTestDefaultInput = `-- name: CreateTestDefaultInput :exec
INSERT INTO test_default_inputs (test_id, data)
VALUES (?, ?)
ON CONFLICT(test_id) DO UPDATE
    SET data = excluded.data
`

type CreateTestDefaultInputParams struct {
	TestID string `json:"test_id"`
	Data   []byte `json:"data"`
}

func (q *Queries) CreateTestDefaultInput(ctx context.Context, arg CreateTestDefaultInputParams) error {
	_, err := q.db.ExecContext(ctx, createTestDefaultInput, arg.TestID, arg.Data)
	return err
}

const deleteTest = `-- name: DeleteTest :exec
DELETE
FROM tests
WHERE id = ?
`

func (q *Queries) DeleteTest(ctx context.Context, id uuid.V7) error {
	_, err := q.db.ExecContext(ctx, deleteTest, id)
	return err
}

const getTest = `-- name: GetTest :one
SELECT id, context_id, test_suite_id, name, has_input, create_time
FROM tests
WHERE id = ?
`

func (q *Queries) GetTest(ctx context.Context, id uuid.V7) (*Test, error) {
	row := q.db.QueryRowContext(ctx, getTest, id)
	var i Test
	err := row.Scan(
		&i.ID,
		&i.ContextID,
		&i.TestSuiteID,
		&i.Name,
		&i.HasInput,
		&i.CreateTime,
	)
	return &i, err
}

const getTestByName = `-- name: GetTestByName :one
SELECT id, context_id, test_suite_id, name, has_input, create_time
FROM tests
WHERE name = ?
  AND test_suite_id = ?
`

type GetTestByNameParams struct {
	Name        string  `json:"name"`
	TestSuiteID uuid.V7 `json:"test_suite_id"`
}

func (q *Queries) GetTestByName(ctx context.Context, arg GetTestByNameParams) (*Test, error) {
	row := q.db.QueryRowContext(ctx, getTestByName, arg.Name, arg.TestSuiteID)
	var i Test
	err := row.Scan(
		&i.ID,
		&i.ContextID,
		&i.TestSuiteID,
		&i.Name,
		&i.HasInput,
		&i.CreateTime,
	)
	return &i, err
}

const getTestDefaultInput = `-- name: GetTestDefaultInput :one
SELECT test_id, data
FROM test_default_inputs
WHERE test_id = ?
`

func (q *Queries) GetTestDefaultInput(ctx context.Context, testID string) (*TestDefaultInput, error) {
	row := q.db.QueryRowContext(ctx, getTestDefaultInput, testID)
	var i TestDefaultInput
	err := row.Scan(&i.TestID, &i.Data)
	return &i, err
}

const listTests = `-- name: ListTests :many
SELECT id, context_id, test_suite_id, name, has_input, create_time
FROM tests
WHERE (context_id = ?1 AND test_suite_id = ?2)
  -- Cast as text required below since sqlc.narg doesn't work with overridden column type
  AND (CAST(?3 AS TEXT) IS NULL OR id < CAST(?3 AS TEXT))
ORDER BY id DESC
LIMIT ?4
`

type ListTestsParams struct {
	ContextID   string  `json:"context_id"`
	TestSuiteID uuid.V7 `json:"test_suite_id"`
	OffsetID    *string `json:"offset_id"`
	PageSize    int64   `json:"page_size"`
}

func (q *Queries) ListTests(ctx context.Context, arg ListTestsParams) ([]*Test, error) {
	rows, err := q.db.QueryContext(ctx, listTests,
		arg.ContextID,
		arg.TestSuiteID,
		arg.OffsetID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Test
	for rows.Next() {
		var i Test
		if err := rows.Scan(
			&i.ID,
			&i.ContextID,
			&i.TestSuiteID,
			&i.Name,
			&i.HasInput,
			&i.CreateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
